import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css'
import { makeStyles } from '@material-ui/core/styles';
import { CssBaseline } from '@material-ui/core';
import Header from '../components/Header';

const useStyles = makeStyles((theme) => ({
  root: {
    minHeight: '100vh',
    backgroundImage: `url(https://images.pexels.com/photos/8647071/pexels-photo-8647071.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260)`,
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
  },
}));

export default function Home() {
  const classes = useStyles();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={classes.root}>
        <CssBaseline />
        <Header />
      </div>
    </>
  );
}
